// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEsLku0XMorWHK7D0Wba5wiv0PyZ7O5ew',
    appId: '1:47953457383:web:144be2a5ada28ecac5b242',
    messagingSenderId: '47953457383',
    projectId: 'krushimitra-8ba6a',
    authDomain: 'krushimitra-8ba6a.firebaseapp.com',
    storageBucket: 'krushimitra-8ba6a.firebasestorage.app',
    measurementId: 'G-7RE5R7L00E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzFgCjq1tk6kQ78Sx_VVD0ONm0puF_DbA',
    appId: '1:47953457383:android:6679d93f9a1f6646c5b242',
    messagingSenderId: '47953457383',
    projectId: 'krushimitra-8ba6a',
    storageBucket: 'krushimitra-8ba6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2FLH6gG8KgH4ge_SlXNls5OllLi2r0B0',
    appId: '1:47953457383:ios:57dbf423b74ea1e1c5b242',
    messagingSenderId: '47953457383',
    projectId: 'krushimitra-8ba6a',
    storageBucket: 'krushimitra-8ba6a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2FLH6gG8KgH4ge_SlXNls5OllLi2r0B0',
    appId: '1:47953457383:ios:57dbf423b74ea1e1c5b242',
    messagingSenderId: '47953457383',
    projectId: 'krushimitra-8ba6a',
    storageBucket: 'krushimitra-8ba6a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1iJb7pEQYLdcpkiawgWk-tPObepckCIw',
    appId: '1:47953457383:web:b95977591a61acfdc5b242',
    messagingSenderId: '47953457383',
    projectId: 'krushimitra-8ba6a',
    authDomain: 'krushimitra-8ba6a.firebaseapp.com',
    storageBucket: 'krushimitra-8ba6a.firebasestorage.app',
    measurementId: 'G-2VX8S14Y5S',
  );
}
